name: 07-MINIONS-PM4
version: 1.9.5
api: 4.0.0
main: 007\Ray\Main
author: RAY007YT
softdepend:
  - EconomyAPI

commands:
  minion:
    description: "get the Minion Spawner!"
permissions:
  minion.commands:
    description: "/minion command permission"
    default: op
  minion.open.others:
    description: "Open other people minions"
    default: op
